In [31]:
import pandas as pd
import numpy as np

In [32]:
df=pd.read_csv('/content/homeprices_banglore.csv')
df.head()

area  bedrooms   price
0  1056         2   39.07
1  2600         4  120.00
2  1440         3   62.00
3  1521         3   75.00
4  1200         2   51.00

In [33]:
from sklearn.preprocessing import MinMaxScaler 
sx=MinMaxScaler()
sy=MinMaxScaler()
scaled_x=sx.fit_transform(df.drop('price',axis='columns').values)
scaled_x

array([[0.08827586, 0.25      ],
       [0.62068966, 0.75      ],
       [0.22068966, 0.5       ],
       [0.24862069, 0.5       ],
       [0.13793103, 0.25      ],
       [0.12758621, 0.25      ],
       [0.6662069 , 0.75      ],
       [0.86206897, 0.75      ],
       [0.17586207, 0.5       ],
       [1.        , 1.        ],
       [0.34482759, 0.5       ],
       [0.68448276, 0.75      ],
       [0.06896552, 0.25      ],
       [0.10344828, 0.25      ],
       [0.5       , 0.5       ],
       [0.12931034, 0.25      ],
       [0.13103448, 0.5       ],
       [0.25517241, 0.5       ],
       [0.67931034, 0.5       ],
       [0.        , 0.        ]])

In [34]:
pd.DataFrame(scaled_x.T)

0        1        2         3         4         5         6   \
0  0.088276  0.62069  0.22069  0.248621  0.137931  0.127586  0.666207   
1  0.250000  0.75000  0.50000  0.500000  0.250000  0.250000  0.750000   

         7         8    9         10        11        12        13   14  \
0  0.862069  0.175862  1.0  0.344828  0.684483  0.068966  0.103448  0.5   
1  0.750000  0.500000  1.0  0.500000  0.750000  0.250000  0.250000  0.5   

        15        16        17       18   19  
0  0.12931  0.131034  0.255172  0.67931  0.0  
1  0.25000  0.500000  0.500000  0.50000  0.0

In [35]:
scaled_y=sy.fit_transform(df['price'].values.reshape(df.shape[0],1))
scaled_y

array([[0.05237037],
       [0.65185185],
       [0.22222222],
       [0.31851852],
       [0.14074074],
       [0.04444444],
       [0.76296296],
       [0.91111111],
       [0.13333333],
       [1.        ],
       [0.37037037],
       [0.8       ],
       [0.04444444],
       [0.05925926],
       [0.51111111],
       [0.07407407],
       [0.11851852],
       [0.20740741],
       [0.51851852],
       [0.        ]])

In [36]:
scaled_y=scaled_y.reshape(scaled_y.shape[0],)
scaled_y

array([0.05237037, 0.65185185, 0.22222222, 0.31851852, 0.14074074,
       0.04444444, 0.76296296, 0.91111111, 0.13333333, 1.        ,
       0.37037037, 0.8       , 0.04444444, 0.05925926, 0.51111111,
       0.07407407, 0.11851852, 0.20740741, 0.51851852, 0.        ])

In [37]:
w=np.ones(shape=(2))
w

array([1., 1.])

In [38]:
b=0
y_predicted = np.dot(w,scaled_x.T) + b
y_predicted

array([0.33827586, 1.37068966, 0.72068966, 0.74862069, 0.38793103,
       0.37758621, 1.4162069 , 1.61206897, 0.67586207, 2.        ,
       0.84482759, 1.43448276, 0.31896552, 0.35344828, 1.        ,
       0.37931034, 0.63103448, 0.75517241, 1.17931034, 0.        ])

In [39]:
np.dot(w,scaled_x.T)

array([0.33827586, 1.37068966, 0.72068966, 0.74862069, 0.38793103,
       0.37758621, 1.4162069 , 1.61206897, 0.67586207, 2.        ,
       0.84482759, 1.43448276, 0.31896552, 0.35344828, 1.        ,
       0.37931034, 0.63103448, 0.75517241, 1.17931034, 0.        ])

In [40]:
(scaled_y-y_predicted)

array([-0.28590549, -0.7188378 , -0.49846743, -0.43010217, -0.24719029,
       -0.33314176, -0.65324393, -0.70095785, -0.54252874, -1.        ,
       -0.47445722, -0.63448276, -0.27452107, -0.29418902, -0.48888889,
       -0.30523627, -0.51251596, -0.54776501, -0.66079183,  0.        ])

In [41]:
scaled_x.T.dot(scaled_y-y_predicted)

array([-4.48682544, -5.54344636])