# Import Libraries

In [24]:
import numpy as np
from tensorflow import keras
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

# Create a short dataset

In [25]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

# Encode words into numbers

In [26]:
one_hot('amazing restaturant',30)

[20, 27]

In [27]:
vocab_size=30
encoded_reviews=[one_hot(d,vocab_size) for d in reviews]
encoded_reviews

[[11, 10],
 [20, 10],
 [22, 11],
 [19, 3, 3],
 [27, 23, 26],
 [14, 10],
 [5, 23, 12],
 [5, 18],
 [5, 12],
 [8, 1]]

# Padding the words

In [28]:
max_length = 3
padded_reviews=pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
padded_reviews

array([[11, 10,  0],
       [20, 10,  0],
       [22, 11,  0],
       [19,  3,  3],
       [27, 23, 26],
       [14, 10,  0],
       [ 5, 23, 12],
       [ 5, 18,  0],
       [ 5, 12,  0],
       [ 8,  1,  0]])

# Create model with 4 feature parameters for each word

In [29]:
embedded_vector_size=4

model=keras.Sequential([
    Embedding(vocab_size,embedded_vector_size,input_length=max_length,name='embedding'),
    keras.layers.Flatten(),
    keras.layers.Dense(1,activation='sigmoid')
])

In [30]:
X=padded_reviews
y=sentiment

In [31]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten_2 (Flatten)         (None, 12)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 13        
                                                                 
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________


In [32]:
model.fit(X,y,epochs=50,verbose=0)

In [33]:
loss,accuracy=model.evaluate(X,y)

1/1 [==============================] - 0s 94ms/step - loss: 0.6382 - accuracy: 0.9000


Since the datatset is small it will give an accuracy of 1

# Get feature weights from the embedding layers

In [34]:
weights=model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [35]:
weights[11]

array([ 0.04742363,  0.0669178 , -0.07017266, -0.00470016], dtype=float32)

In [36]:
weights[20]

array([ 0.03697557,  0.03877307, -0.00303275, -0.04995831], dtype=float32)