# Import libraries

In [1]:
import tensorflow_hub as hub
import tensorflow_text as text

In [2]:
encoder_url='https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'
preprocess_url='https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'

In [3]:
bert_preprocess_model=hub.KerasLayer(preprocess_url)


In [4]:
text_test=['nice movie indeed','I love python programming']
text_preprocessed=bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_type_ids', 'input_word_ids', 'input_mask'])

# Masks for each sentence

In [5]:
text_preprocessed['input_mask']
# CLS [sentence] SEP

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

# Word ID for each word in the sentence

In [6]:
text_preprocessed['input_word_ids']
# CLS [sentence] SEP

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [7]:
bert_model=hub.KerasLayer(encoder_url)
bert_results=bert_model(text_preprocessed)
bert_results.keys()


dict_keys(['encoder_outputs', 'pooled_output', 'sequence_output', 'default'])

# Embedding for the entire sentence

In [8]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.7917743 , -0.21411934,  0.4976949 , ...,  0.24465166,
        -0.4733449 ,  0.81758726],
       [-0.9171231 , -0.4793518 , -0.78656983, ..., -0.6175176 ,
        -0.7102687 ,  0.92184293]], dtype=float32)>

# Each sentence has padding and each word is represented by a vector

In [9]:
bert_results['sequence_output']
# [sentence] 0 0 0 0 0 <-- 128 as it is a contexualized sentence

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292042,  0.08567819,  0.14476846, ..., -0.09677091,
          0.08722158,  0.07711089],
        [ 0.17839484, -0.19006062,  0.50349456, ..., -0.05869824,
          0.3271712 , -0.15578577],
        [ 0.18701512, -0.43388787, -0.4887515 , ..., -0.1550272 ,
          0.0014518 , -0.24471004],
        ...,
        [ 0.12083051,  0.12884259,  0.46453547, ...,  0.0737555 ,
          0.17441949,  0.16522136],
        [ 0.07967859, -0.01190698,  0.50225425, ...,  0.13777778,
          0.2100223 ,  0.00624579],
        [-0.07212703, -0.28303495,  0.5903335 , ...,  0.4755193 ,
          0.16668479, -0.08920302]],

       [[-0.07900573,  0.36335123, -0.2110158 , ..., -0.17183736,
          0.1629973 ,  0.67242646],
        [ 0.2788349 ,  0.4371635 , -0.35764754, ..., -0.04463583,
          0.38315123,  0.5887979 ],
        [ 1.2037661 ,  1.072702  ,  0.48408687, ...,  0.24921006,
          0.4073092 ,  0.404818  ],
        ...,

In [10]:
len(bert_results['encoder_outputs'])
# small BASE BERT with 12 encoders


12

# Encoder output for all encoders

In [11]:
bert_results['encoder_outputs'][0]


<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.12901427,  0.00644756, -0.03614959, ...,  0.04999617,
          0.06149195, -0.02657554],
        [ 1.1753383 ,  1.2140788 ,  1.156998  , ...,  0.11634377,
         -0.3585539 , -0.4049023 ],
        [ 0.03859045,  0.5386999 , -0.21089773, ...,  0.21858215,
          0.7260168 , -1.1158609 ],
        ...,
        [-0.07587016, -0.2542193 ,  0.7075512 , ...,  0.5054201 ,
         -0.18878648,  0.15028323],
        [-0.16066599, -0.28089675,  0.5759705 , ...,  0.5275856 ,
         -0.11141355,  0.0288752 ],
        [-0.04428156, -0.20279586,  0.59093523, ...,  0.8133835 ,
         -0.3907579 , -0.02601741]],

       [[ 0.18903571,  0.02752551, -0.06513739, ..., -0.00620209,
          0.15053877,  0.03165431],
        [ 0.59161484,  0.75891393, -0.07240683, ...,  0.6190397 ,
          0.8292891 ,  0.16161966],
        [ 1.4460826 ,  0.4460267 ,  0.40990284, ...,  0.48255897,
          0.6269113 ,  0.13463378],
        ...,

In [12]:
bert_results['encoder_outputs'][-1]==bert_results['sequence_output']
# Encoder output for last encoder is same as sequence output


<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>